name: Notify via Telegram

on:
  push:
    branches:
      - main  # Or your working branch name

jobs:
  send-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="🚀 New update pushed to *main*! Check it out on GitHub Pages." \
            -d parse_mode=Markdown
